{"uuid": "d4c986af-5f9a-4f14-a85f-52e70b7c26a4", "children": ["3a7d7f6d-2ba9-44dc-b0ee-de64fe0ddc3f", "760c4fdc-2496-4d19-a7c9-c774c17cda28", "8ddc23c4-fff2-46a6-8608-f03a4cee568d"], "befores": [{"name": "env", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/Users/icsoc/work/pytest/config/env_config.yml'\n", "trace": "  File \"/Users/icsoc/.virtualenvs/pytest/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/icsoc/.virtualenvs/pytest/lib/python3.6/site-packages/_pytest/fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/icsoc/.virtualenvs/pytest/lib/python3.6/site-packages/_pytest/fixtures.py\", line 782, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/icsoc/work/pytest/test/conftest.py\", line 15, in env\n    with open(config_path) as f:\n"}, "start": 1548919799270, "stop": 1548919799270}], "start": 1548919799270, "stop": 1548919799358}